apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_DATABASE: bXlzcWw=
  MYSQL_USER: dXNlcm5hbWU=
  MYSQL_PASSWORD: cGFzc3dvcmQ=


