apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: phpbb
spec:
  selector:
    app: phpbb
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      nodePort: 30080
  type: NodePort

